name: Build savedefconfig
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Kernel repository link'
        default: 'anggitmrt87/kernel_xiaomi_citrus_sm6115'
        required: true
      branch:
        description: 'Kernel repository branch'
        default: '13.0.0-perf'
        required: true
      toolchain_url:
        description: 'Custom Clang toolchain URL (optional)'
        required: false
        default: ''

jobs:
  build:
    strategy:
      matrix:
        include:
          - device: bengal-perf
          - device: bengal-stock
    uses: ./.github/workflows/regen-script.yml
    with:
      repo: ${{ inputs.repo }}
      branch: ${{ inputs.branch }}
      device: ${{ matrix.device }}
      toolchain_url: ${{ inputs.toolchain_url }}
